# *Numpy*

# ***importing numpy***

In [1]:
import numpy as np
# Set seed for reproducibility
np.random.seed(seed=1234)

# ***scaler***

In [2]:
arr = np.array(6)

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

6
0
()
1
int64


# ***using list***

In [3]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.array(list)

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5 6 7 8 9]
1
(9,)
9
int64


# ***using matrix -> 2D***

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype = float)

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
2
(3, 3)
9
float64


# ***numpy basic function***

In [5]:
print("creating a vector with 0...")
a = np.zeros(5)
print(a)

print("\ncreating a matrix(n*n) with 0...")
a = np.zeros((5, 5))
print(a)

print("\ncreating a matrix(n*n) with 1...")
a = np.ones((3, 3), dtype = int)
print(a)
print("dimention : ", a.ndim)
print("shape : ", a.shape)
print("size : ", a.size)
print("data type : ", a.dtype)


print("\ncreating an identity matrix...")
a = np.eye(5)
print(a)


print("\ncreating an matrix with random number...")
a = np.random.random((4, 4))
print(a)
print(a.dtype)

creating a vector with 0...
[0. 0. 0. 0. 0.]

creating a matrix(n*n) with 0...
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

creating a matrix(n*n) with 1...
[[1 1 1]
 [1 1 1]
 [1 1 1]]
dimention :  2
shape :  (3, 3)
size :  9
data type :  int64

creating an identity matrix...
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

creating an matrix with random number...
[[0.19151945 0.62210877 0.43772774 0.78535858]
 [0.77997581 0.27259261 0.27646426 0.80187218]
 [0.95813935 0.87593263 0.35781727 0.50099513]
 [0.68346294 0.71270203 0.37025075 0.56119619]]
float64


# ***printing array using nested for loop***

In [6]:
n =  int(input("enter the value of n : "))

arr = np.eye(n, dtype = int)

for i in arr:
    for j in i:
        print(j, end = " ")
    print()

for i in range(0, n):
    for j in range(0, n):
        arr[i][j] = int(input(f"matrix{i, j} : "))

print("\nmatrix : \n", arr)

enter the value of n :  2


1 0 
0 1 


matrix(0, 0) :  1
matrix(0, 1) :  2
matrix(1, 0) :  3
matrix(1, 1) :  4



matrix : 
 [[1 2]
 [3 4]]


# ***operation of numpy***

In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])

summation = np.add(a, b)
subtraction = np.subtract(a, b)
multiplication = np.multiply(a, b)


print("using normal method : ")
print('summation : \n', a+b)
print('subtraction : \n', a-b)
print('multiplication : \n', a*b)


print("\n\nusing numpy method : ")
print('summation : \n', summation)
print('subtraction : \n', subtraction)
print('multiplication : \n', multiplication)

using normal method : 
summation : 
 [[5 5]
 [5 5]]
subtraction : 
 [[-3 -1]
 [ 1  3]]
multiplication : 
 [[4 6]
 [6 4]]


using numpy method : 
summation : 
 [[5 5]
 [5 5]]
subtraction : 
 [[-3 -1]
 [ 1  3]]
multiplication : 
 [[4 6]
 [6 4]]


# ***dot product***

In [8]:
a = np.array([[1,2,3], [4,5,6]], dtype = float)
b = np.array([[7,8], [9,10], [11, 12]], dtype = float)

# rowa == colb(must)

ans = a.dot(b)

print("a : \n", a)
print('shape of a : ', a.shape)

print("\nb : \n", b)
print('shape of b : ', b.shape)

print("\nans : \n", ans)
print('shape of ans : ', ans.shape)

a : 
 [[1. 2. 3.]
 [4. 5. 6.]]
shape of a :  (2, 3)

b : 
 [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
shape of b :  (3, 2)

ans : 
 [[ 58.  64.]
 [139. 154.]]
shape of ans :  (2, 2)


## ***cross product***

In [9]:
a = np.array([[1,2], [3,4]])
b = np.array([[5, 6], [7, 8]])
# rowa == rowb and cola = colb(must)

ans = np.cross(a, b)

print("a : \n", a)
print('shape of a : ', a.shape)

print("\nb : \n", b)
print('shape of b : ', b.shape)

print("\nans : \n", ans)
print('shape of ans : ', ans.shape)

a : 
 [[1 2]
 [3 4]]
shape of a :  (2, 2)

b : 
 [[5 6]
 [7 8]]
shape of b :  (2, 2)

ans : 
 [-4 -4]
shape of ans :  (2,)


C:\Users\Maruf\AppData\Local\Temp\ipykernel_11044\3454191080.py:5: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  ans = np.cross(a, b)


# ***extra fanction***

In [10]:
# very important feature
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# matrix
# 1 2 3
# 4 5 6
# 7 8 9

print('total sum : ', np.sum(arr))
print('column sum : ', np.sum(arr, axis = 0))
print('row sum : ', np.sum(arr, axis = 1))


print(arr.min())
print(arr.min(axis = 0)) # min of column
print(arr.min(axis = 1)) # min of row

print(arr.max())
print(arr.max(axis = 0)) # max of column
print(arr.max(axis = 1)) # max of row

total sum :  45
column sum :  [12 15 18]
row sum :  [ 6 15 24]
1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


# ***broadcasting***

In [11]:
a = np.array([1, 2, 3])
b = np.array(5)

ans = a + b
print(ans)

[6 7 8]
